default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password:
  host: localhost
  database: Wishify_development

test:
  <<: *default
  username: root
  password:
  host: localhost
  database: Wishify_test

production:
  <<: *default
  database: Wishify_production
  username: Wishify
  password: <%= ENV["WISHIFY_DATABASE_PASSWORD"] %>
